import {
    StyleSheet
} from 'react-native';

const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#fff',
        alignItems:'center',
        justifyContent:'center'
    },
    saleSty1:{
        padding:20,
        height:130,
        width:'100%',
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center'
    },
    saleSty2:{
        flexDirection:'row',
        alignItems:'center'
    },
    saleSty3:{
        paddingLeft:10
    },
    saleSty4:{
        flexDirection:'row',
        backgroundColor:'#eeeeee',
    },
    itemCap:{
        textAlign:'center',
        paddingVertical:10,
        flex:1,
    },
    saleSty5:{
        width:'100%',
        flexDirection:'row',
        paddingVertical:20
    },
    itemList:{
        textAlign:'center',
        flex:1,
        fontSize:25
    },
    saleSty6:{
        flex:1,
        width:'100%',
    },
    saleSty7:{
        flexDirection:'row',
        alignItems:'center',
        width:'100%',
        justifyContent:'space-between',
        paddingHorizontal:30,
        backgroundColor:'#eeeeee'
    },
    saleSty8:{
        flexDirection:'row',
        marginVertical:10,
    },
    saleSty9:{
        width:'100%',
    },
    saleSty10:{
        justifyContent:'flex-end',
        flexDirection:'row',
        padding:20,
        width:'100%',
        alignItems:'center'
    },
    saleSty11:{
        color:'#fd8d09',
        fontSize:30
    },
    saleSty12:{
        marginLeft:30,
        fontSize:20
    },
    saleSty13:{
        width:'100%',
        alignItems:'flex-end',
        paddingRight:20,
        marginBottom:20,
    },
    saleSty14:{
        backgroundColor:'#fd8d09',
        color:'#ffffff',
        width:240,
        paddingVertical:20,
        textAlign:'center',
        letterSpacing:3,
        fontSize:18
    },
    saleSty15:{
        height:150,
        width:'100%',
    },
    textSize:{
        fontSize:20
    },
    saleSty16:{
        width:200,
        borderWidth:1,
        borderColor:'rgba(0,0,0,.2)',
        height:40,
        paddingLeft:10
    }

})

export default styles